# Generated by Django 3.2.7 on 2021-10-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_body', models.CharField(max_length=50)),
                ('operational_body', models.CharField(max_length=50)),
                ('operator_username', models.CharField(max_length=50)),
                ('operational_time', models.DateTimeField(auto_now=True)),
                ('operator_role', models.CharField(max_length=50)),
                ('operating_level', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'systems_log',
            },
        ),
    ]
