# Generated by Django 3.2.7 on 2021-09-17 01:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('website_id', models.AutoField(primary_key=True, serialize=False)),
                ('website_uuid', models.CharField(max_length=200, verbose_name='网站唯一编码')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('website_name', models.CharField(max_length=200, verbose_name='网站名称')),
                ('background_image', models.ImageField(null=True, upload_to='images/', verbose_name='网站首页背景图片')),
                ('website_logo', models.ImageField(null=True, upload_to='images/', verbose_name='网站logo')),
            ],
            options={
                'verbose_name': '网站配置',
                'verbose_name_plural': '信息',
                'db_table': 'website_info',
            },
        ),
    ]
