# Generated by Django 3.2.7 on 2021-09-17 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteManagementapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name': '网站配置', 'verbose_name_plural': '基础信息'},
        ),
    ]
