# Generated by Django 3.2.7 on 2021-09-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(null=True, upload_to='booktest', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_describe',
            field=models.TextField(max_length=4000),
        ),
    ]
