# Generated by Django 3.2.7 on 2021-09-16 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_auto_20210916_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_owner',
            field=models.CharField(default=1, max_length=200, verbose_name='产品负责人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_updateTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后一次修改时间'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_address',
            field=models.CharField(max_length=200, verbose_name='产品地址'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_body',
            field=models.CharField(max_length=200, verbose_name='产品内容'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_describe',
            field=models.TextField(max_length=4000, verbose_name='产品描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_state',
            field=models.CharField(max_length=200, verbose_name='产品状态'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(max_length=200, verbose_name='产品类型'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_uuid',
            field=models.CharField(max_length=200, verbose_name='产品编号'),
        ),
    ]
