# Generated by Django 3.2.7 on 2021-09-16 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_auto_20210916_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '产品', 'verbose_name_plural': '产品'},
        ),
    ]
