# Generated by Django 3.2.7 on 2021-09-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_address',
            field=models.CharField(max_length=200, verbose_name='商品地址'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_body',
            field=models.CharField(max_length=200, verbose_name='商品内容'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_describe',
            field=models.TextField(max_length=4000, verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_owner',
            field=models.CharField(max_length=200, verbose_name='商品负责人'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_state',
            field=models.CharField(max_length=200, verbose_name='商品状态'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], max_length=200, verbose_name='商品类型'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_uuid',
            field=models.CharField(max_length=200, verbose_name='商品编号'),
        ),
    ]
