# Generated by Django 3.2.7 on 2021-09-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_auto_20210916_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='production_cycle',
            field=models.CharField(choices=[(1, '10天交付'), (2, '30天交付'), (3, '45天交付'), (4, '60天交付'), (5, '90天交付'), (6, '半年及以上')], default=1, max_length=200, verbose_name='商品生产周期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_state',
            field=models.CharField(choices=[(1, '在售'), (2, '已下架'), (3, '停产')], max_length=200, verbose_name='商品状态'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[(1, 'VPX系统'), (2, '解决方案')], max_length=200, verbose_name='商品类型'),
        ),
    ]
