# Generated by Django 3.2.7 on 2021-09-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0007_auto_20210916_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='图片'),
        ),
    ]
